openapi: 3.0.0
info:
  title: HatchUp
  version: 1.0.0
  description: HatchUpプロジェクトのAPIドキュメントです。

paths:
  /api/admin/check:
    $ref: "./app/api/admin/check/admin-check.yaml"
  /api/aiagent/messages:
    $ref: "./app/api/aiagent/messages/aiagent-messages.yaml"
  /api/aiagent/session:
    $ref: "./app/api/aiagent/session/aiagent-session.yaml"
  /api/aiagent/setup:
    $ref: "./app/api/aiagent/setup/aiagent-setup.yaml"
  /api/aiagent/test-microcms:
    $ref: "./app/api/aiagent/test-microcms/aiagent-test-microcms.yaml"
  /api/aiagent:
    $ref: "./app/api/aiagent/aiagent.yaml"
  /api/auth/content-snare-callback:
    $ref: "./app/api/auth/content-snare-callback/content-snare-callback.yaml"
  /api/cancel-subscription:
    $ref: "./app/api/cancel-subscription/cancel-subscription.yaml"
  /api/content-snare/admin/fetch-full-status:
    $ref: "./app/api/content-snare/admin/fetch-full-status/admin-fetch-full-status.yaml"
  /api/content-snare/admin/get-request-pages:
    $ref: "./app/api/content-snare/admin/get-request-pages/admin-get-request-pages.yaml"
  /api/content-snare/admin/get-request-status:
    $ref: "./app/api/content-snare/admin/get-request-status/admin-get-request-status.yaml"
  /api/content-snare/admin/get-templates:
    $ref: "./app/api/content-snare/admin/get-templates/admin-get-templates.yaml"
  /api/content-snare/admin/list-requests:
    $ref: "./app/api/content-snare/admin/list-requests/admin-list-requests.yaml"
  /api/content-snare/auth-code:
    $ref: "./app/api/content-snare/auth-code/auth-code.yaml"
  /api/content-snare/auth-status:
    $ref: "./app/api/content-snare/auth-status/auth-status.yaml"
  /api/content-snare/check-status:
    $ref: "./app/api/content-snare/check-status/check-status.yaml"
  /api/content-snare/client-search:
    $ref: "./app/api/content-snare/client-search/client-search.yaml"
  /api/content-snare/create-client:
    $ref: "./app/api/content-snare/create-client/create-client.yaml"
  /api/content-snare/create-request:
    $ref: "./app/api/content-snare/create-request/create-request.yaml"
  /api/content-snare/create-submission:
    $ref: "./app/api/content-snare/create-submission/create-submission.yaml"
  /api/content-snare/exchange-token:
    $ref: "./app/api/content-snare/exchange-token/exchange-token.yaml"
  /api/content-snare/get-applications:
    $ref: "./app/api/content-snare/get-applications/get-applications.yaml"
  /api/content-snare/get-request-status:
    $ref: "./app/api/content-snare/get-request-status/get-request-status.yaml"
  /api/content-snare/oauth-direct:
    $ref: "./app/api/content-snare/oauth-direct/oauth-direct.yaml"
  /api/content-snare/refresh-token:
    $ref: "./app/api/content-snare/refresh-token/refresh-token.yaml"
  /api/content-snare/webhook:
    $ref: "./app/api/content-snare/webhook/webhook.yaml"
  /api/course-application/create:
    $ref: "./app/api/course-application/create/course-application-create.yaml"
  /api/course-application/details:
    $ref: "./app/api/course-application/details/course-application-details.yaml"
  /api/course-application/schedules:
    $ref: "./app/api/course-application/schedules/course-application-schedules.yaml"
  /api/course-application/status:
    $ref: "./app/api/course-application/status/course-application-status.yaml"
  /api/create-customer-portal-session:
    $ref: "./app/api/create-customer-portal-session/create-customer-portal-session.yaml"
  /api/create-subscription:
    $ref: "./app/api/create-subscription/create-subscription.yaml"
  /api/events:
    $ref: "./app/api/events/events.yaml"
  /api/job-positions:
    $ref: "./app/api/job-positions/job-positions.yaml"
  /api/microcms:
    $ref: "./app/api/microcms/microcms.yaml"
  /api/schools/[id]/courses/[courseId]/intake-dates:
    $ref: "./app/api/schools/[id]/courses/[courseId]/intake-dates/courses-intake-dates.yaml"
  /api/schools/[id]/courses/[courseId]/job-positions:
    $ref: "./app/api/schools/[id]/courses/[courseId]/job-positions/courses-job-positions.yaml"
  /api/schools/[id]/courses/[courseId]/subjects:
    $ref: "./app/api/schools/[id]/courses/[courseId]/subjects/courses-subjects.yaml"
  /api/schools/[id]/courses/[courseId]:
    $ref: "./app/api/schools/[id]/courses/[courseId]/schools-courses-courseId.yaml"
  /api/schools/[id]/courses:
    $ref: "./app/api/schools/[id]/courses/schools-courses.yaml"

components:
  responses:
    # 共通のBad Request (400) レスポンス
    BadRequest:
      description: リクエストの形式が不正です。必須パラメータの不足や値の形式が間違っています。
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "質問が指定されていません"

    # 共通のUnauthorized (401) レスポンス
    UnauthorizedError:
      description: 認証エラー。有効な認証情報が提供されていません。
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "認証情報が不正です"

    # 共通のNot Found (404) レスポンス
    NotFound:
      description: 指定したリソースが見つかりません。
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "リソースが見つかりません"

    # 共通のInternal Server Error (500) レスポンス
    InternalServerError:
      description: サーバーエラー。予期せぬ問題が発生しました。
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: string
                example: "予期せぬエラーが発生しました"
